### ISSUE TITLE
WSLで動かない

### ISSUE THREAD

**Issue by chvmvd** [ut-code/uplace#13]
`WEB_ORIGIN`が`http://localhost:5173/`になっているため、WSLで動かないです。ここ適切に変えないといけなそうです。

**Comment by aster-void** [comment]
再現お願いされました！ (このサークル Windows ユーザー少なすぎ)

**Comment by aster-void** [comment]
自分の環境では動きましたよ。

**Comment by chvmvd** [comment]
じゃあ、いいか。
